#!/bin/bash

if [[ ! -e "$ESPA_CONFIG_PATH/.usgs/.cfgnfo" ]]; then
	echo "Missing Database configuration $ESPA_CONFIG_PATH/.usgs/.cfgnfo"
	exit 1
fi

#python -m unittest discover test
nose2 --verbose --fail-fast --with-coverage

# flake8 api
# pylint api

